apiVersion: v1
kind: Service
metadata:
  name: mongo-service
  namespace: kub2
spec:
  selector:
    role: mongo
  ports:
    - protocol: TCP
      port: 27017
      targetPort: 27017
  clusterIP: None
