apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongo-deployment
  namespace: theclusterexcercise1
  labels:
    app: mongo-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongo-deployment
  template:
    metadata:
      labels:
        app: mongo-deployment
    spec:
      containers:
        - name: mongo
          image: mongo:latest
          resources:
            requests:
              memory: "64Mi"
              cpu: "250m"
            limits:
              memory: "512Mi"
              cpu: "500m"
          ports:
            - containerPort: 27017
          #volumeMounts:
          #  - name: mongo-volume
          #    mountPath: /data/db
          env:
            - name: MONGO_INITDB_ROOT_USERNAME
              valueFrom:
                secretKeyRef:
                  name: db-secret
                  key: MONGO_INITDB_ROOT_USERNAME
            - name: MONGO_INITDB_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-secret
                  key: MONGO_INITDB_ROOT_PASSWORD
      #volumes:
      #  - name: mongo-volume
      #    persistentVolumeClaim:
      #      claimName: mongo-volume-pvc
