apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongo-volume-pvc
  namespace: theclusterexcercise1
spec:
  storageClassName: "nfs-client"
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
